version: '3'

services:
  #PHP Service
  apache-l58:
    build: .
    container_name: apache-l58-cont
    volumes:
      - ../:/var/www/html/
    ports:
      - "5002:80"
    depends_on:
      - db
 
  #MySQL Service
  db:
    image: mysql
    container_name: db-l58-cont
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: l58
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql